//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NovaCash.Sportsbook.Clients.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NovaCash.Sportsbook.Clients.Resources.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stake.
        /// </summary>
        public static string stake {
            get {
                return ResourceManager.GetString("stake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no data..
        /// </summary>
        public static string ThereIsNoData {
            get {
                return ResourceManager.GetString("ThereIsNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trans_id.
        /// </summary>
        public static string trans_id {
            get {
                return ResourceManager.GetString("trans_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vendor_member_id.
        /// </summary>
        public static string vendor_member_id {
            get {
                return ResourceManager.GetString("vendor_member_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to winlost_amount.
        /// </summary>
        public static string winlost_amount {
            get {
                return ResourceManager.GetString("winlost_amount", resourceCulture);
            }
        }
    }
}
